In [34]:
# Ankush Mukhedkar (Email: amuk8580@gmail.com)
# For ShapeAI boot camp project

#mount the drive as the file is in google collab folder
#from google.colab import drive  
#drive.mount('/content/drive') 
#Check if the drive has been mounted
#!ls

#Import required libraries
import pandas
import numpy

#read the contents of CSV file and create a data frame out of it
df = pandas.DataFrame(pandas.read_csv('/content/drive/My Drive/ColabNotebooks/train (1).csv'))
df.head()
df.shape

nCols = df.isnull().sum() #counts the number of null values per column

drop_col = nCols[nCols > ((df.shape[0]) * 35/100)]  #get columns which are having null values above 35% of total row count
#drop_col
#drop_col.index
df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()
df.corr()

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

df['Embarked'].describe()  #see the count, unique, top, frequency of top
df['Embarked'].fillna('S',inplace=True)  #fill-in the blanks with the value for top frequency
df.isnull().sum()   #There shouldn't be any nulls by now
df.corr()   #check the corelation now
 
df['FamilySize'] = df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'], axis=1, inplace=True)
df.corr()
 
df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.groupby(['Alone'])['Survived'].mean()
df[['Alone','Fare']].corr()
 
df['Sex']= [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()
 
df.groupby(['Embarked'])['Survived'].mean()
df.corr()

             PassengerId  Survived    Pclass  ...      Fare  FamilySize     Alone
PassengerId     1.000000 -0.005007 -0.035144  ...  0.012658   -0.040143  0.057462
Survived       -0.005007  1.000000 -0.338481  ...  0.257307    0.016639 -0.203367
Pclass         -0.035144 -0.338481  1.000000  ... -0.549500    0.065997  0.135207
Sex            -0.042939  0.543351 -0.131900  ...  0.182333    0.200988 -0.303646
Age             0.033207 -0.069809 -0.331339  ...  0.091566   -0.248512  0.179775
Fare            0.012658  0.257307 -0.549500  ...  1.000000    0.217138 -0.271832
FamilySize     -0.040143  0.016639  0.065997  ...  0.217138    1.000000 -0.690922
Alone           0.057462 -0.203367  0.135207  ... -0.271832   -0.690922  1.000000

[8 rows x 8 columns]

Conclusion: 

*   Female Passengers were prioritized over men.
*   People with high class or rich people have higher survival rate than others.
*   The hierarchy might have been followed while saving the passengers.
*   Passengers travelling with their family have higher survival rate.
*   Passengers who boarded the ship at Cherbourg, survived more in proportion than the others.